// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list_recent_journals.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_journals_default = defineTool({
  name: "list_recent_journals",
  title: "List recent trade journals",
  description: "List the signed-in user's most recent trade journal entries (\u9519\u9898\u96C6), newest first. Returns id, symbol, direction, outcome, entry reason, and simulated time.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Max journals to return (1-50)."),
    symbol: z.string().trim().optional().describe("Optional symbol filter, e.g. BTCUSDT."),
    outcome: z.enum(["win", "loss", "breakeven", "no_entry"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, symbol, outcome }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb(ctx).from("trade_journals").select("id, symbol, direction, post_outcome, pre_entry_reason, pre_simulated_time, post_review_summary").eq("user_id", ctx.getUserId()).order("pre_simulated_time", { ascending: false }).limit(limit);
    if (symbol) q = q.eq("symbol", symbol);
    if (outcome) q = q.eq("post_outcome", outcome);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { journals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_journal.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_journal_default = defineTool2({
  name: "get_journal",
  title: "Get trade journal by id",
  description: "Fetch one full trade journal row (pre-trade snapshot + post-trade review) for the signed-in user.",
  inputSchema: {
    journal_id: z2.string().uuid().describe("Trade journal UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ journal_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb2(ctx).from("trade_journals").select("*").eq("id", journal_id).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Journal not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { journal: data }
    };
  }
});

// src/lib/mcp/tools/list_trading_rules.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_trading_rules_default = defineTool3({
  name: "list_trading_rules",
  title: "List trading rules",
  description: "List the signed-in user's trading rules (checklist derived from the error catalog).",
  inputSchema: {
    only_active: z3.boolean().default(true).describe("Only return rules where is_active = true.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_active }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb3(ctx).from("trading_rules").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (only_active) q = q.eq("is_active", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rules: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_error_patterns.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_error_patterns_default = defineTool4({
  name: "list_error_patterns",
  title: "List error tag patterns",
  description: "List the signed-in user's error tag patterns (\u4E2A\u4EBA\u9519\u9898\u6807\u7B7E), sorted by occurrence count. Useful for seeing which mistake patterns recur most.",
  inputSchema: {
    include_archived: z4.boolean().default(false),
    limit: z4.number().int().min(1).max(100).default(30)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_archived, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb4(ctx).from("error_tag_patterns").select("id, category_id, pattern_name, operational_definition, occurrence_count, last_seen_at, is_archived").eq("user_id", ctx.getUserId()).order("occurrence_count", { ascending: false }).limit(limit);
    if (!include_archived) q = q.eq("is_archived", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { patterns: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.0";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool5({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's profile: user id, email, display name, initial capital, initialized state.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb5(ctx).from("profiles").select("user_id, display_name, initial_capital, is_initialized").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      profile: data
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pyvndfzpbsgzinqxairn";
var mcp_default = defineMcp({
  name: "trading-journal-mcp",
  title: "\u4EA4\u6613\u590D\u76D8\u4E2D\u5FC3 MCP",
  version: "0.1.0",
  instructions: "Tools for the trading journal / \u9519\u9898\u96C6 app. Every tool acts as the signed-in user via Supabase RLS. Use `whoami` to confirm identity, `list_recent_journals` and `get_journal` to review trade journals, `list_error_patterns` to inspect recurring mistake patterns, and `list_trading_rules` to see the user's active checklist.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_recent_journals_default, get_journal_default, list_error_patterns_default, list_trading_rules_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
