-- Safety Net · trade_journals 列对齐
-- 设计意图：
--   远程库经常滞后于本地代码（用户没跑所有 migration），导致 finalizeJournalReview 的 schema
--   fallback 把整个 extra payload 剥光，所有评价字段写不进去——错题集汇总因此全是 0/N。
--   这一份迁移用 ADD COLUMN IF NOT EXISTS 把当前代码用到的所有列一次性补齐，幂等可重跑。
--   跑过这次之后，未来的开仓快照 / 平仓评价就能完整保存。

ALTER TABLE public.trade_journals
  -- ============ Pre · 决策结构 ============
  ADD COLUMN IF NOT EXISTS pre_thesis_why_right                    text,
  ADD COLUMN IF NOT EXISTS pre_premortem_failure_reason            text,
  ADD COLUMN IF NOT EXISTS pre_falsification_signal                text,
  ADD COLUMN IF NOT EXISTS pre_confidence_basis                    text,
  ADD COLUMN IF NOT EXISTS pre_odds_structure                      text,
  ADD COLUMN IF NOT EXISTS pre_odds_structure_source               text,
  ADD COLUMN IF NOT EXISTS pre_odds_structure_premortem            text,
  ADD COLUMN IF NOT EXISTS pre_odds_structure_breakdown_signals    text,
  ADD COLUMN IF NOT EXISTS pre_account_equity_usdt                 numeric,
  ADD COLUMN IF NOT EXISTS pre_opportunity_cost_worth              boolean,
  ADD COLUMN IF NOT EXISTS pre_cheap_opportunity                   text,
  ADD COLUMN IF NOT EXISTS pre_edge_source                         text,
  ADD COLUMN IF NOT EXISTS pre_market_regime                       text,
  ADD COLUMN IF NOT EXISTS pre_entry_stage                         text,
  ADD COLUMN IF NOT EXISTS pre_stop_quality                        text,
  ADD COLUMN IF NOT EXISTS pre_chase_after_close                   boolean,
  ADD COLUMN IF NOT EXISTS pre_calibration_win_pct                 numeric,
  -- ============ Pre · 信息 / 情绪 / 偏差标签 ============
  ADD COLUMN IF NOT EXISTS pre_info_kline_facts                    text,
  ADD COLUMN IF NOT EXISTS pre_info_macro_facts                    text,
  ADD COLUMN IF NOT EXISTS pre_info_rule_advice                    text,
  ADD COLUMN IF NOT EXISTS pre_info_intuition                      text,
  ADD COLUMN IF NOT EXISTS pre_info_designer_view                  text,
  ADD COLUMN IF NOT EXISTS pre_opponent_statement                  text,
  ADD COLUMN IF NOT EXISTS pre_pain_tags                           text[],
  ADD COLUMN IF NOT EXISTS pre_cognitive_bias_tags                 text[],
  ADD COLUMN IF NOT EXISTS pre_triggered_principle_ids             text[],
  ADD COLUMN IF NOT EXISTS pre_triggered_rule_ids                  text[],
  -- ============ Pre · Stop Doing List ============
  ADD COLUMN IF NOT EXISTS pre_stop_doing_acknowledged_ids         uuid[],
  ADD COLUMN IF NOT EXISTS pre_stop_doing_ad_hoc                   text,
  -- ============ Post · 基础复盘 ============
  ADD COLUMN IF NOT EXISTS post_result_summary                     text,
  ADD COLUMN IF NOT EXISTS post_decision_quality                   text,
  ADD COLUMN IF NOT EXISTS post_struggle_level                     integer,
  ADD COLUMN IF NOT EXISTS post_small_position_drag                text,
  ADD COLUMN IF NOT EXISTS post_missed_high_odds_state             text,
  ADD COLUMN IF NOT EXISTS post_path_mode                          text,
  ADD COLUMN IF NOT EXISTS post_path_first_move                    text,
  ADD COLUMN IF NOT EXISTS post_path_drawdown                      text,
  ADD COLUMN IF NOT EXISTS post_path_win_quality                   text,
  ADD COLUMN IF NOT EXISTS post_path_agency_note                   text,
  ADD COLUMN IF NOT EXISTS post_trade_agency_score                 integer,
  ADD COLUMN IF NOT EXISTS post_positive_expectancy_review         text,
  ADD COLUMN IF NOT EXISTS post_premortem_review                   text,
  ADD COLUMN IF NOT EXISTS post_invalidation_review                text,
  ADD COLUMN IF NOT EXISTS post_entry_payoff_basis_review          text,
  ADD COLUMN IF NOT EXISTS post_entry_win_rate_basis_review        text,
  ADD COLUMN IF NOT EXISTS post_opponent_was_right                 boolean,
  ADD COLUMN IF NOT EXISTS post_real_close_time                    timestamptz,
  ADD COLUMN IF NOT EXISTS exit_falsification_status               text,
  ADD COLUMN IF NOT EXISTS exit_falsification_note                 text,
  -- ============ Post · 情绪侧七问 + 主石头 ============
  ADD COLUMN IF NOT EXISTS post_emo_disturbance                    text,
  ADD COLUMN IF NOT EXISTS post_emo_first_reaction                 text,
  ADD COLUMN IF NOT EXISTS post_emo_wanted                         text,
  ADD COLUMN IF NOT EXISTS post_emo_feared                         text,
  ADD COLUMN IF NOT EXISTS post_emo_excuse                         text,
  ADD COLUMN IF NOT EXISTS post_emo_main_stone                     text,
  ADD COLUMN IF NOT EXISTS post_emo_main_stone_tags                text[],
  ADD COLUMN IF NOT EXISTS post_emo_next_time_plan                 text,
  -- ============ 对冲 ============
  ADD COLUMN IF NOT EXISTS hedge_type                              text,
  ADD COLUMN IF NOT EXISTS hedge_boundary_price                    numeric,
  ADD COLUMN IF NOT EXISTS hedge_boundary_basis                    text,
  ADD COLUMN IF NOT EXISTS hedge_boundary_stance                   text,
  ADD COLUMN IF NOT EXISTS hedge_lock_profit_pct                   numeric,
  ADD COLUMN IF NOT EXISTS hedge_resolution_up                     text,
  ADD COLUMN IF NOT EXISTS hedge_resolution_down                   text,
  ADD COLUMN IF NOT EXISTS hedge_down_if_chop                      text,
  ADD COLUMN IF NOT EXISTS hedge_down_if_trend                     text,
  ADD COLUMN IF NOT EXISTS hedge_down_if_rebound                   text,
  ADD COLUMN IF NOT EXISTS hedge_necessity_pct                     numeric,
  ADD COLUMN IF NOT EXISTS hedge_safety_strength                   integer,
  ADD COLUMN IF NOT EXISTS hedge_safety_regularity                 integer,
  ADD COLUMN IF NOT EXISTS hedge_risk_magnitude                    integer,
  ADD COLUMN IF NOT EXISTS hedge_conviction_pct                    numeric,
  ADD COLUMN IF NOT EXISTS hedge_friction_cost                     text,
  ADD COLUMN IF NOT EXISTS hedge_order_method                      text,
  ADD COLUMN IF NOT EXISTS hedge_worth_it                          text,
  -- ============ 其他 ============
  ADD COLUMN IF NOT EXISTS order_kind                              text,
  ADD COLUMN IF NOT EXISTS journal_kind                            text,
  ADD COLUMN IF NOT EXISTS no_trade_reason                         text,
  ADD COLUMN IF NOT EXISTS no_trade_would_be_entry_price           numeric,
  ADD COLUMN IF NOT EXISTS no_trade_direction                      text,
  ADD COLUMN IF NOT EXISTS campaign_id                             uuid,
  ADD COLUMN IF NOT EXISTS leg_role                                text,
  ADD COLUMN IF NOT EXISTS leg_sequence                            integer;
